
# Серверы
servers:
  # Имя тестового стенда
  testStand: "Stand_N1"

# Файлы с данными
dataFiles:
  standsDataFilePath: "data/stand_1/stands.yaml"
  clientsDataFilePath: "data/stand_1/clients.yaml"

# Люди
people:
  # Фамилия тестового клиента, участвующего в тестах
  client: "Автотестюк"
